# Generated by Django 4.2.6 on 2023-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
