# Generated by Django 4.2.6 on 2023-10-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0002_alter_user_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='shortened_urls',
            field=models.JSONField(null=True),
        ),
    ]
