# Generated by Django 4.2.6 on 2023-10-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0003_user_data_shortened_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Password',
            field=models.TextField(default='test'),
        ),
    ]
